"""Initial PM tables

Revision ID: 524c47a390c5
Revises: 
Create Date: 2026-01-27 01:30:23.921805+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '524c47a390c5'
down_revision = None
branch_labels = None
depends_on = None

CONST_SCHEMA = "pm"

def upgrade() -> None:
    # Create the schema if it doesn't exist
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {CONST_SCHEMA}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='pm'
    )
    op.create_index('idx_attachments_entity', 'attachments', ['entity_type', 'entity_id'], unique=False, schema='pm')
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['pm.comments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pm'
    )
    op.create_index('idx_comments_entity', 'comments', ['entity_type', 'entity_id'], unique=False, schema='pm')
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='pm'
    )
    op.create_index('idx_teams_project_id', 'teams', ['project_id'], unique=False, schema='pm')
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['pm.teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pm'
    )
    op.create_index('idx_projects_owner_id', 'projects', ['owner_id'], unique=False, schema='pm')
    op.create_index('idx_projects_project_type', 'projects', ['project_type'], unique=False, schema='pm')
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False, schema='pm')
    op.create_table('team_members',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['pm.teams.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'user_id'),
    schema='pm'
    )
    op.create_index('idx_team_members_team_id', 'team_members', ['team_id'], unique=False, schema='pm')
    op.create_index('idx_team_members_user_id', 'team_members', ['user_id'], unique=False, schema='pm')
    op.create_table('milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['pm.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pm'
    )
    op.create_index('idx_milestones_project_id', 'milestones', ['project_id'], unique=False, schema='pm')
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('actual_hours', sa.Float(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['pm.tasks.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['pm.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pm'
    )
    op.create_index('idx_tasks_assigned_to', 'tasks', ['assigned_to'], unique=False, schema='pm')
    op.create_index('idx_tasks_priority', 'tasks', ['priority'], unique=False, schema='pm')
    op.create_index('idx_tasks_project_id', 'tasks', ['project_id'], unique=False, schema='pm')
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False, schema='pm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tasks_status', table_name='tasks', schema='pm')
    op.drop_index('idx_tasks_project_id', table_name='tasks', schema='pm')
    op.drop_index('idx_tasks_priority', table_name='tasks', schema='pm')
    op.drop_index('idx_tasks_assigned_to', table_name='tasks', schema='pm')
    op.drop_table('tasks', schema='pm')
    op.drop_index('idx_milestones_project_id', table_name='milestones', schema='pm')
    op.drop_table('milestones', schema='pm')
    op.drop_index('idx_team_members_user_id', table_name='team_members', schema='pm')
    op.drop_index('idx_team_members_team_id', table_name='team_members', schema='pm')
    op.drop_table('team_members', schema='pm')
    op.drop_index('idx_projects_status', table_name='projects', schema='pm')
    op.drop_index('idx_projects_project_type', table_name='projects', schema='pm')
    op.drop_index('idx_projects_owner_id', table_name='projects', schema='pm')
    op.drop_table('projects', schema='pm')
    op.drop_index('idx_teams_project_id', table_name='teams', schema='pm')
    op.drop_table('teams', schema='pm')
    op.drop_index('idx_comments_entity', table_name='comments', schema='pm')
    op.drop_table('comments', schema='pm')
    op.drop_index('idx_attachments_entity', table_name='attachments', schema='pm')
    op.drop_table('attachments', schema='pm')
    # ### end Alembic commands ###

    # Optionally drop the schema (commented out for safety)
    # op.execute(f"DROP SCHEMA IF EXISTS {CONST_SCHEMA}")
