"""Domain layer exports."""

from serp_products.domain.entities import (
    AttributeDefinition,
    BillOfMaterials,
    BoMLine,
    Category,
    PriceList,
    PriceRule,
    Product,
    ProductAttribute,
    ProductUoM,
    UnitOfMeasure,
)
from serp_products.domain.events import (
    AttributeDefinitionCreated,
    AttributeDefinitionUpdated,
    BillOfMaterialsCreated,
    BillOfMaterialsUpdated,
    CategoryCreated,
    CategoryUpdated,
    PriceListCreated,
    PriceListUpdated,
    PriceRuleUpdated,
    ProductActivated,
    ProductCreated,
    ProductDeactivated,
    ProductDeleted,
    ProductUpdated,
    UnitOfMeasureCreated,
    UnitOfMeasureUpdated,
)
from serp_products.domain.repositories import (
    IAttributeDefinitionRepository,
    IBillOfMaterialsRepository,
    ICategoryRepository,
    IPriceListRepository,
    IProductRepository,
    IUnitOfMeasureRepository,
)
from serp_products.domain.services import (
    BoMCostCalculator,
    PriceCalculator,
    ProductSearchService,
    ProductVariantGenerator,
    UnitConverter,
)
from serp_products.domain.value_objects import (
    AttributeDataType,
    AttributeValue,
    Barcode,
    CategoryPath,
    ConversionFactor,
    Measurement,
    ProductCode,
    ProductType,
    UoMCategory,
)

__all__ = [
    # Entities
    "UnitOfMeasure",
    "AttributeDefinition",
    "Category",
    "Product",
    "ProductAttribute",
    "ProductUoM",
    "PriceList",
    "PriceRule",
    "BillOfMaterials",
    "BoMLine",
    # Value Objects
    "ProductCode",
    "ProductType",
    "UoMCategory",
    "AttributeDataType",
    "AttributeValue",
    "Measurement",
    "ConversionFactor",
    "Barcode",
    "CategoryPath",
    # Repositories
    "IUnitOfMeasureRepository",
    "IAttributeDefinitionRepository",
    "ICategoryRepository",
    "IProductRepository",
    "IPriceListRepository",
    "IBillOfMaterialsRepository",
    # Services
    "UnitConverter",
    "ProductVariantGenerator",
    "PriceCalculator",
    "BoMCostCalculator",
    "ProductSearchService",
    # Events
    "UnitOfMeasureCreated",
    "UnitOfMeasureUpdated",
    "AttributeDefinitionCreated",
    "AttributeDefinitionUpdated",
    "CategoryCreated",
    "CategoryUpdated",
    "ProductCreated",
    "ProductUpdated",
    "ProductDeleted",
    "ProductActivated",
    "ProductDeactivated",
    "PriceListCreated",
    "PriceListUpdated",
    "PriceRuleUpdated",
    "BillOfMaterialsCreated",
    "BillOfMaterialsUpdated",
]
