"""add_dm_models

Revision ID: 7e798e3c4aa7
Revises: 
Create Date: 2026-01-28 02:48:52.795210+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e798e3c4aa7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dm'
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False, schema='dm')
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False, schema='dm')
    op.create_index('idx_audit_timestamp', 'audit_logs', ['timestamp'], unique=False, schema='dm')
    op.create_index('idx_audit_user_id', 'audit_logs', ['user_id'], unique=False, schema='dm')
    op.create_table('document_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='dm'
    )
    op.create_index('idx_doctypes_category', 'document_types', ['category'], unique=False, schema='dm')
    op.create_index('idx_doctypes_code', 'document_types', ['code'], unique=True, schema='dm')
    op.create_table('folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['dm.folders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dm'
    )
    op.create_index('idx_folders_parent_id', 'folders', ['parent_id'], unique=False, schema='dm')
    op.create_index('idx_folders_path', 'folders', ['project_id', 'path'], unique=False, schema='dm')
    op.create_index('idx_folders_project_id', 'folders', ['project_id'], unique=False, schema='dm')
    op.create_table('stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dm'
    )
    op.create_index('idx_stages_order', 'stages', ['project_id', 'order_index'], unique=False, schema='dm')
    op.create_index('idx_stages_project_id', 'stages', ['project_id'], unique=False, schema='dm')
    op.create_table('storage_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dm'
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('document_type_id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('version_scheme', sa.String(length=20), nullable=True),
    sa.Column('current_version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('external_references', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['dm.document_types.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['dm.folders.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['dm.stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number'),
    schema='dm'
    )
    op.create_index('idx_documents_document_number', 'documents', ['document_number'], unique=True, schema='dm')
    op.create_index('idx_documents_document_type_id', 'documents', ['document_type_id'], unique=False, schema='dm')
    op.create_index('idx_documents_folder_id', 'documents', ['folder_id'], unique=False, schema='dm')
    op.create_index('idx_documents_project_id', 'documents', ['project_id'], unique=False, schema='dm')
    op.create_index('idx_documents_stage_id', 'documents', ['stage_id'], unique=False, schema='dm')
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False, schema='dm')
    op.create_table('template_folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['dm.template_folders.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['dm.storage_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='dm'
    )
    op.create_index('idx_template_folders_template_id', 'template_folders', ['template_id'], unique=False, schema='dm')
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_string', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('request_note', sa.Text(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['dm.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='dm'
    )
    op.create_index('idx_approvals_assigned_to', 'approval_requests', ['assigned_to'], unique=False, schema='dm')
    op.create_index('idx_approvals_document_id', 'approval_requests', ['document_id'], unique=False, schema='dm')
    op.create_index('idx_approvals_status', 'approval_requests', ['status'], unique=False, schema='dm')
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_string', sa.String(length=20), nullable=False),
    sa.Column('major', sa.Integer(), nullable=True),
    sa.Column('minor', sa.Integer(), nullable=True),
    sa.Column('patch', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('generated_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['dm.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='dm'
    )
    op.create_index('idx_versions_document_id', 'document_versions', ['document_id'], unique=False, schema='dm')
    op.create_index('idx_versions_version_string', 'document_versions', ['document_id', 'version_string'], unique=False, schema='dm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_versions_version_string', table_name='document_versions', schema='dm')
    op.drop_index('idx_versions_document_id', table_name='document_versions', schema='dm')
    op.drop_table('document_versions', schema='dm')
    op.drop_index('idx_approvals_status', table_name='approval_requests', schema='dm')
    op.drop_index('idx_approvals_document_id', table_name='approval_requests', schema='dm')
    op.drop_index('idx_approvals_assigned_to', table_name='approval_requests', schema='dm')
    op.drop_table('approval_requests', schema='dm')
    op.drop_index('idx_template_folders_template_id', table_name='template_folders', schema='dm')
    op.drop_table('template_folders', schema='dm')
    op.drop_index('idx_documents_status', table_name='documents', schema='dm')
    op.drop_index('idx_documents_stage_id', table_name='documents', schema='dm')
    op.drop_index('idx_documents_project_id', table_name='documents', schema='dm')
    op.drop_index('idx_documents_folder_id', table_name='documents', schema='dm')
    op.drop_index('idx_documents_document_type_id', table_name='documents', schema='dm')
    op.drop_index('idx_documents_document_number', table_name='documents', schema='dm')
    op.drop_table('documents', schema='dm')
    op.drop_table('storage_templates', schema='dm')
    op.drop_index('idx_stages_project_id', table_name='stages', schema='dm')
    op.drop_index('idx_stages_order', table_name='stages', schema='dm')
    op.drop_table('stages', schema='dm')
    op.drop_index('idx_folders_project_id', table_name='folders', schema='dm')
    op.drop_index('idx_folders_path', table_name='folders', schema='dm')
    op.drop_index('idx_folders_parent_id', table_name='folders', schema='dm')
    op.drop_table('folders', schema='dm')
    op.drop_index('idx_doctypes_code', table_name='document_types', schema='dm')
    op.drop_index('idx_doctypes_category', table_name='document_types', schema='dm')
    op.drop_table('document_types', schema='dm')
    op.drop_index('idx_audit_user_id', table_name='audit_logs', schema='dm')
    op.drop_index('idx_audit_timestamp', table_name='audit_logs', schema='dm')
    op.drop_index('idx_audit_entity', table_name='audit_logs', schema='dm')
    op.drop_index('idx_audit_action', table_name='audit_logs', schema='dm')
    op.drop_table('audit_logs', schema='dm')
    # ### end Alembic commands ###

