"""add_projects_and_stage_templates

Revision ID: d33e5dd597a3
Revises: 7e798e3c4aa7
Create Date: 2026-01-28 17:59:13.831261+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33e5dd597a3'
down_revision = '7e798e3c4aa7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pm_project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('stage_template_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dm'
    )
    op.create_index('idx_projects_pm_id', 'projects', ['pm_project_id'], unique=True, schema='dm')
    op.create_table('stage_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dm'
    )
    op.create_table('stage_template_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['dm.stage_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='dm'
    )
    op.create_index('idx_stage_template_items_template_id', 'stage_template_items', ['template_id'], unique=False, schema='dm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stage_template_items_template_id', table_name='stage_template_items', schema='dm')
    op.drop_table('stage_template_items', schema='dm')
    op.drop_table('stage_templates', schema='dm')
    op.drop_index('idx_projects_pm_id', table_name='projects', schema='dm')
    op.drop_table('projects', schema='dm')
    # ### end Alembic commands ###
