"""Domain layer exports."""

from serp_inventory.domain.entities import (
    AdjustmentLine,
    InventoryAdjustment,
    LotSerial,
    ReorderingRule,
    StockLocation,
    StockMove,
    StockQuant,
    Warehouse,
)
from serp_inventory.domain.events import (
    InventoryAdjustmentCancelled,
    InventoryAdjustmentConfirmed,
    InventoryAdjustmentCreated,
    LotSerialCreated,
    ReorderingRuleCreated,
    ReorderingRuleTriggered,
    StockLocationCreated,
    StockMoveCancelled,
    StockMoveConfirmed,
    StockMoveCreated,
    StockMoveExecuted,
    StockQuantAdded,
    StockQuantityAdded,
    StockQuantityRemoved,
    StockQuantityReserved,
    StockQuantityUnreserved,
    StockReservationFulfilled,
    WarehouseActivated,
    WarehouseCreated,
    WarehouseDeactivated,
)
from serp_inventory.domain.repositories import (
    IInventoryAdjustmentRepository,
    ILotSerialRepository,
    IReorderingRuleRepository,
    IStockLocationRepository,
    IStockMoveRepository,
    IStockQuantRepository,
    IWarehouseRepository,
)
from serp_inventory.domain.value_objects import (
    AdjustmentNumber,
    AdjustmentReason,
    AdjustmentState,
    CostingMethod,
    LocationCode,
    LocationType,
    LocationUsage,
    LotSerialNumber,
    MovementNumber,
    ReorderRoute,
    StockMoveState,
    StockMoveType,
    StockQuantity,
)

__all__ = [
    # Entities
    "Warehouse",
    "StockLocation",
    "StockQuant",
    "StockMove",
    "InventoryAdjustment",
    "AdjustmentLine",
    "ReorderingRule",
    "LotSerial",
    # Value Objects
    "LocationCode",
    "LocationType",
    "LocationUsage",
    "StockMoveType",
    "StockMoveState",
    "AdjustmentReason",
    "AdjustmentState",
    "CostingMethod",
    "ReorderRoute",
    "MovementNumber",
    "AdjustmentNumber",
    "StockQuantity",
    "LotSerialNumber",
    # Repositories
    "IWarehouseRepository",
    "IStockLocationRepository",
    "IStockQuantRepository",
    "IStockMoveRepository",
    "IInventoryAdjustmentRepository",
    "IReorderingRuleRepository",
    "ILotSerialRepository",
    # Events
    "WarehouseCreated",
    "WarehouseActivated",
    "WarehouseDeactivated",
    "StockLocationCreated",
    "StockQuantAdded",
    "StockQuantityAdded",
    "StockQuantityRemoved",
    "StockQuantityReserved",
    "StockQuantityUnreserved",
    "StockReservationFulfilled",
    "StockMoveCreated",
    "StockMoveConfirmed",
    "StockMoveExecuted",
    "StockMoveCancelled",
    "InventoryAdjustmentCreated",
    "InventoryAdjustmentConfirmed",
    "InventoryAdjustmentCancelled",
    "ReorderingRuleCreated",
    "ReorderingRuleTriggered",
    "LotSerialCreated",
]
